export const SHOW_NEWS = "SHOW_NEWS";
export const SHOW_POST = "SHOW_POST";

export const LOAD_ARTICLES = "LOAD_ARTICLES";
export const GET_ARTICLES_SUCCES = "GET_ARTICLES_SUCCES";
export const ARTICLES_TOTAL_COUNTS = "ARTICLES_TOTAL_COUNTS";
export const SORTED_ARTICLES = "SORTED_ARTICLES";

export const LOAD_POSTS = "LOAD_POSTS";
export const GET_POST_SUCCES = "GET_POST_SUCCES";
export const SORTED_POSTS = "SORTED_POSTS";